"""add document_summary link table and extra_prompt

Revision ID: 740361fab1eb
Revises: 08687cee41db
Create Date: 2025-12-01 17:17:09.867415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '740361fab1eb'
down_revision: Union[str, None] = '08687cee41db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_summaries',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('summary_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['summary_id'], ['summaries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id', 'summary_id')
    )
    op.add_column('summaries', sa.Column('extra_prompt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('summaries', 'extra_prompt')
    op.drop_table('document_summaries')
    # ### end Alembic commands ###
